AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Resources:
  TransitServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TransitService
      Description: A simple AWS Lambda function in Scala
      Runtime: java8
      Handler: lambda.ApiGatewayProxyHandler
      CodeUri: target/scala-2.13/transit-service.jar
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          env: prod
      Events:
        GetTransitDepartures:
          Type: Api
          Properties:
            Path: /default/transitService
            Method: GET
        
Outputs:
    ApiURL:
      Description: "API endpoint URL for Prod environment"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/default/transitService"
